[colors.bright]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x3c3836"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x282828"
foreground = "0xd4be98"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[[keyboard.bindings]]
action = "Last"
key = 5
mode = "Vi"
mods = "Shift"

[window]
dynamic_title = true
opacity = 0.95
